### ISSUE TITLE
Edit homepage another browser.

### ISSUE THREAD

**Issue by misterchikite** [Zavy86/WikiDocs#217] opened 2024-11-25 16:29 UTC
### Describe your issue

Hello,

I am running Wikidocs via Docker on a Synology.

When I try to edit the home page (for example) using a different browser, it doesn’t work.

I enter the password to authenticate, but I am redirected to the same page without the toolbar appearing.

I’m not sure if this issue has already been reported.

I find Wikidocs very useful and would like to implement it within my team.

Thank you for your help.

### Device and settings

Container on Synology DSM 7.2

### Steps to reproduce

Container on Synology DSM 7.2

### Extra fields

- [ ] I'd like to work on this issue

**Comment by ffiesta** [comment] 2024-11-25 16:58
Can you attach some images, or errors, urls to help identify your issue!

**Comment by ffiesta** [comment] 2024-11-25 17:03
Please check Marius hosting how to: https://mariushosting.com/how-to-install-wikidocs-on-your-synology-nas/

After validation, if you continue to have problems, come back here!

**Comment by misterchikite** [comment] 2024-11-26 09:42
I followed the installation tutorial from Marius Hosting.
I tried once using Portainer and another time with Synology's container service.

The result is the same in both cases.

It's hard to provide a screenshot or error message since I don't get any error.

Here's what happens:

I enter the password :
![2024-11-26_10h38_14](https://github.com/user-attachments/assets/f249f379-a06d-4560-8211-3decfcaa81c4)

Then, it simply returns to the previous screen :
![2024-11-26_10h38_36](https://github.com/user-attachments/assets/cd15bb07-7738-43d0-831f-3860825ea73d)

Do you have any suggestions or solutions?

Thank you in advance for your help!

**Comment by ffiesta** [comment] 2024-11-26 10:02
Hello, wikidocs has 2 passwords 1 with only read access and another with read/write access!

I won't know if you are using read or write password, but if 2 password is iqual you need to insert 2 times!
Can you check

**Comment by misterchikite** [comment] 2024-11-26 10:21
I just recreated the container and entered the password for the first time (on the configuration page).  
Using the same browser, I can use this password to edit or add a page without any issue.  

However, when I switch to a different browser and access the same URL, using the same password has no effect.  

Could you clarify where the two passwords are configured? On the configuration page, there seems to be only one password to set.

**Comment by ffiesta** [comment] 2024-11-26 10:30
In configuration, please try same password 2 times in the lock (upper right corner)

You insert 2 2 passwords on settings gear 

See example image without view password
![Screenshot_20241126-102449_Chrome](https://github.com/user-attachments/assets/62303c9f-c224-4910-87bf-cc174290ca7a)

- The edit password is required 
- The view password it only need if you want to hide all content


Another question, which browsers you are using?

**Comment by ffiesta** [comment] 2024-11-26 11:48
Until now nobody identify that issue!

It's hard to help because i need to have a synology to try replicate your issue, but i know that wikidocs works fine in multiple browsers! I tested on a few!

Can you make some tests
1. Change edit password to **123456**
2. Change/add view password to **xpto**
3. Create multiple pages on wikidocs 
4. Logout from wikidocs
5. Close browser
6. Open try to access and create new wikidoc.
7. Repeat with non work browser!

Let me know what happened!

**Comment by misterchikite** [comment] 2024-11-26 12:01
Well, I just tested on another Synology with a local IP and the problem is similar.

Another detail: when I enter the password, I don't get the "Authentication successful" pop-up.

I set the password to "test" and everything is the same.

Can I send you my URL in a private message so you understand what I mean?

**Comment by ffiesta** [comment] 2024-11-26 12:44
Can you check if docker created error log on installation folder?

Yes you can send!

> But we need other guys with synology to identify problem!

**Comment by ffiesta** [comment] 2024-11-26 13:13
@misterchikite - What version of wikidocs you setup on synology runing?

**Comment by ffiesta** [comment] 2024-11-27 14:38
@misterchikite have you tried another version?

If you run in wikidocs 1.0.65 can you trie change session from 500 to 2600 on flie classes\Session.class.php  line 45 to see if it solve problem!

**Comment by misterchikite** [comment] 2024-11-28 14:12
I don't have any errors in the logs. 
Yes, I'm running version 1.0.65. I wasn't able to create a Docker with version 1.0.63.

Do you know where I can find the file "classes\Session.class.php"? I only have access to the Docker\Wikidocs folder and the "config.inc.php" file.

Thank you and sorry for not replying earlier.

**Comment by ffiesta** [comment] 2024-11-28 15:11
You need to acces directly to wikidocs folder, and go to subfolder classes!

About try 1.0.63 down't downgrade from 1.0.65, make a clean install with new domain onlybto test.

**Comment by misterchikite** [comment] 2024-11-28 16:42
I can't select another image version. In the tags, there's only the "Latest" tag. 

https://hub.docker.com/r/zavy86/wikidocs/tags

Do you know how I can do it? Directly with GitHub?
Can you give me the link to enter in "container manager" or "Portainer"?

Thanks.

**Comment by Zavy86** [comment] 2024-12-01 14:49
@misterchikite I have added some tags:

:latest for the last release
:1 for all 1.X.X releases
:1.0 for all 1.0.X releases
:1.0.67 for the fixed release

![Screenshot 2024-12-01 at 15 44 29](https://github.com/user-attachments/assets/d98f49a8-d5bc-4c00-9d28-9dd8aae254bd)

**Comment by chris-we-2024** [comment] 2024-12-01 18:28
Hello, I have the same problem. Change the Browser, or start on another day, my password doesn't work. After deleting the config.inc.php file in /wikidata a new initialize wikodocs work. I think that the Version 1.0.65 was OK.

**Comment by misterchikite** [comment] 2024-12-02 15:19
Thank you @Zavy86,

Could you add version 1.0.65 to the tags?

Thank you, I just tested version 1.0.69 and the issue is still present.

**Comment by leomoon** [comment] 2024-12-02 19:51
this is version 1.65 which we had code block fix:
https://github.com/Zavy86/WikiDocs/commit/311603c26106ac54cb2ba5b0666de0528e9080b4

The later versions did not change that much to make it not work!

This sounds like htaccess issue.

**Comment by Zavy86** [comment] 2024-12-02 20:20
try with the last one release.
try to add ?debug=1 to the URL and paste here some debug info..
are you using a local path or a volume for the datasets?

**Comment by JDO139** [comment] 2024-12-05 18:06
I'm having the same issue as the original post. I started editing my wikidocs on my iPhone and when I went home to work on the page with my PC, the authentication code just sends me back to the page with no editing tools in the top.

**Comment by hammeri** [comment] 2024-12-05 21:25
Also having the same issue, tried to edit and unable to get past the authentication code. If I delete the config.inc.php file, restart the image and reconfigure Wikidocs then the authentication code will work as expected. If I close and re-open the browser then I am back to being unable to get past the authentication code.

**Comment by ffiesta** [comment] 2024-12-05 21:59
Hi @JDO139, hi @hammeri where is your wikidocs running? Docker, synology, cpanel?

**Comment by JDO139** [comment] 2024-12-05 23:16
@ffiesta 

Mine is on Docker. And looks like I can replicate it. If I delete the config file, I'm able to go back into admin settings and go through the initial configuration wizard and then continue editing. However, if I open a new browser or access the wiki on another device, I cannot log back into edit/admin mode.

**Comment by Zavy86** [comment] 2024-12-06 06:13
@JDO139 are you using compose?
docker volume or local host path?
maybe is a permission issue?
operating system?

**Comment by leomoon** [comment] 2024-12-06 08:02
I can replicate it with docker-compose.
https://www.youtube.com/watch?v=v1oTXYdSSDA

This does not happen with my setup using manual php server and nginx.

**Comment by leomoon** [comment] 2024-12-06 08:26
I know whyyyyyy

**Comment by leomoon** [comment] 2024-12-06 08:31
Fix for this
https://github.com/Zavy86/WikiDocs/pull/226

**Comment by hammeri** [comment] 2024-12-06 08:59
@ffiesta
Mine is running on a Proxmox VM running Ubuntu using a portainer stack.

**Comment by misterchikite** [comment] 2024-12-06 13:45
Thank you, Leomoon,

I just tested the freshly released version 1.0.71, and it works.

Thank you for your work, it's amazing!

**Comment by hammeri** [comment] 2024-12-06 13:55
Confirmed working on my config with 1.0.71 - Many thanks

**Closed** 2024-12-06 17:00 UTC
Labels: bug
